version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Authenticating with Amazon ECR…
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050137142.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image…
      - docker build -t platform_anchorage_backend .
      - docker tag platform_anchorage_backend:latest 975050137142.dkr.ecr.us-east-1.amazonaws.com/platform_anchorage_backend:latest
  post_build:
    commands:
      - echo Pushing the Docker image…
      - docker push 975050137142.dkr.ecr.us-east-1.amazonaws.com/platform_anchorage_backend:latest
artifacts:
  files:
    - 'Dockerrun.aws.json'
